apiVersion: fbi.h-da.de/v1alpha1
kind: JVB
metadata:
  name: jvb-manager
spec:
  size: 1
  name: jvb
  services:
    - kind: Service
      apiVersion: v1
      metadata:
        name: WILL_BE_REPLACED
        labels:
      spec:
        ports:
          - name: jvb-http
            protocol: TCP
            port: 80
            targetPort: 8080
        selector:
        type: ClusterIP
    - kind: Service
      apiVersion: v1
      metadata:
        name: WILL_BE_REPLACED
        labels:
      spec:
        ports:
          - name: jvb-tcp
            protocol: TCP
            port: 443
            targetPort: 443
            nodePort: 30240
        selector:
        clusterIP: 172.30.213.174
        type: LoadBalancer
    - kind: Service
      apiVersion: v1
      metadata:
        name: WILL_BE_REPLACED
        labels:
      spec:
        ports:
          - name: jvb
            protocol: UDP
            port: 10000
            targetPort: 10000
            nodePort: 31884
        selector:
        clusterIP: 172.30.213.17
        type: LoadBalancer

  jvbDeployment:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
      name: WILL_BE_REPLACED
      labels:
    spec:
      replicas: 0
      selector:
        matchLabels:
      template:
        metadata:
          labels:
        spec:
          containers:
            - resources: {}
              readinessProbe:
                httpGet:
                  path: /about/health
                  port: 8080
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              name: jvb
              livenessProbe:
                httpGet:
                  path: /about/health
                  port: 8080
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              env:
                - name: JVB_AUTH_USER
                  valueFrom:
                    secretKeyRef:
                      name: jitsi
                      key: JVB_AUTH_USER
                - name: JVB_AUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: jitsi
                      key: JVB_AUTH_PASSWORD
                - name: DOCKER_HOST_ADDRESS
                  value: WILL_BE_REPLACED
              ports:
                - name: jvb
                  containerPort: 10000
                  protocol: UDP
                - name: jvb-tcp
                  containerPort: 443
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: config
                  mountPath: /config
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: jitsi
              image: 'jitsi/jvb:4101'
          serviceAccount: jvb
          volumes:
            - name: config
              emptyDir: {}
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
