apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jitsis.jitsi.fbi.h-da.de
spec:
  group: jitsi.fbi.h-da.de
  names:
    kind: Jitsi
    listKind: JitsiList
    plural: jitsis
    singular: jitsi
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Jitsi is the Schema for the jitsis API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: JitsiSpec defines the desired state of Jitsi
            properties:
              size:
                format: int32
                type: integer
            required:
            - size
            type: object
          status:
            description: JitsiStatus defines the observed state of Jitsi
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
