apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jitsi-operator
  template:
    metadata:
      labels:
        name: jitsi-operator
    spec:
      serviceAccountName: jitsi-operator
      containers:
        - name: jitsi-operator
          image: koehlerlukas/jitsi-operator
          command:
          - jitsi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jitsi-operator"
